# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2018.03.07-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-9.0-h13b8566_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2019.0-118.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/jpeg-8d-2.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/lcms-1.19-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-8.2.0-hdf63c60_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-8.2.0-hdf63c60_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cudnn-7.1.2-cuda9.0_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/jbig-2.1-hdba287a_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libffi-3.2.1-hd88cf55_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.16-h1bed415_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2019.0-118.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/nccl-1.3.5-cuda9.0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.1-hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1-h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.4-h14c3975_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/zlib-1.2.11-ha838bed_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20170329-h6b74fdf_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.35-hbc83047_0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/libtiff-4.0.6-2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/readline-7.0-h7b6447c_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.8-hbc83047_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.2.5-hf484d3e_1.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/freetype-2.5.5-2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.25.2-h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-2.7.15-h9bab390_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/backcall-0.1.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/backports-1.0-py27_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/backports_abc-0.5-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2018.10.15-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/decorator-4.3.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/enum34-1.1.6-py27_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/futures-3.2.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipython_genutils-0.2.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ninja-1.8.2-py27h6bb024c_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.15.4-py27h81de0dd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/olefile-0.46-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/parso-0.3.1-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/pil-1.1.7-py27_2.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/pillow-3.4.2-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ptyprocess-0.6.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pycparser-2.19-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2018.7-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-17.1.2-py27h14c3975_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scandir-1.9.0-py27h14c3975_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/simplegeneric-0.8.1-py27_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/six-1.11.0-py27_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/wcwidth-0.1.7-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/backports.shutil_get_terminal_size-1.0.0-py27_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.11.5-py27he75722e_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.13.1-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pathlib2-2.3.2-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pexpect-4.6.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-dateutil-2.7.5-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-40.5.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/singledispatch-3.4.0.3-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-4.3.2-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_core-4.4.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pickleshare-0.7.5-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pygments-2.2.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-5.1.1-py27h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.32.2-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_client-5.2.3-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pip-18.1-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/prompt_toolkit-1.0.15-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipython-5.8.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-4.10.0-py27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.0.6-py27h7dd41cf_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.0.1-py27h4414c95_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.15.4-py27h1d66e8a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandas-0.23.4-py27h04863e7_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytorch-0.4.1-py27ha74772b_0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/torchvision-0.1.8-py27_0.tar.bz2
